config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, :skip => [:registrations]
  devise_for :members
  root 'site/home#index'

  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources 'admins', except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :member
  belongs_to :category
end

app/models/admin.rb
class Admin < ApplicationRecord
	enum role: [:full_access, :restricted_access]

  scope :with_full_access, -> {(where role: 'full_access')}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def role_br
    	if role == 'full_access'
    		'Acesso Completo'
    	else
    		'Acesso Restrito'
    	end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates_presence_of :description
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 
  layout :layout_by_resource

  protected

  def layout_by_resource
  	if devise_controller? && resource_name == :admin
  		"backoffice_devise"
  	else
  		"application"
  	end
  end

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController

	before_action :set_admin, only: [:edit, :update, :destroy]

  def index
  	@admins = Admin.all
  end

  def new
    @admin = Admin.new
  end
   
  def create
    @admin = Admin.new(params_admin)

    if @admin.save
      redirect_to backoffice_admins_path, notice: "O administrador #{@admin.email} foi cadastrado com sucesso!"
    else
      render 'new'
    end

  end

  def edit
  end

  def update

  	pwd = params[:admin][:password]
    pwd_confirmation = params[:admin][:password_confirmation]

  	if pwd.blank? && pwd_confirmation.blank?
  		params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
  	end

    if @admin.update(params_admin)
      redirect_to backoffice_admins_path, notice: "O administrador #{@admin.email} foi atualizado com sucesso!"
    else
      render 'new'
    end
  end

  def destroy

    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O administrador #{@admin.email} foi excluído com sucesso!"
    else
      render :index
    end

  end

  private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      params.require(:admin).permit(:name, :role, :email, :password, :password_confirmation)
    end

end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]

  def index
  	@categories = Category.all
  end

  def new
    @category = Category.new
  end
   
  def create
    @category = Category.new(params_category)

    if @category.save
      redirect_to backoffice_categories_path, notice: "A categoria #{@category.description} foi cadastrada com sucesso!"
    else
      render 'new'
    end

  end

  def edit
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "A categoria #{@category.description} foi atualizada com sucesso!"
    else
      render 'new'
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def params_category
      params.require(:category).permit(:description)
    end

end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController

  def index
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	before_action :authenticate_admin!
  layout "backoffice"
end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
	
	layout "site"

  def index
  	@categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %>
<%# end -%>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %>
<%# end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Editar Administrador"} %> 

app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Administradores</h1>
<div class="panel panel-default">
        <div class="panel-heading">
            Administradores
            <%= link_to new_backoffice_admin_path, class:"btn btn-success btn-sm pull-right", style: "margin-top: -5px" do %><i class="fa fa-plus"></i> Novo Admin
            <% end %>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>Tipo de acesso</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @admins.each do |admin| %>
                        <tr>
                            <td><%= admin.id %></td>
                            <td><%= admin.name %></td>
                            <td><%= admin.email %></td>
                            <td><%= admin.role_br %></td>
                            <td>
                              <%= link_to edit_backoffice_admin_path(admin),class:"btn btn-primary btn-circle" do %><i class="fa fa-edit"></i>
                              <% end %>

                              <% if current_admin.id != admin.id %>
                                <%= link_to backoffice_admin_path(admin), method: :delete, class:"btn btn-danger btn-circle", data: {confirm: "Você deseja excluir #{admin.email}?"} do %><i class="fa fa-times"></i>
                                <% end %>
                              <% else %>
                                <%= link_to '#', disabled:"disabled", class:"btn btn-danger btn-circle" do %><i class="fa fa-times"></i>
                                <% end %>
                              <% end %>
                              </button>
                            </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Novo Administrador"} %> 

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>
  <% if @admin.errors.full_messages.each do |message| %>
    <script>
    $.notify("<%= message %>", "error");
    </script>
    <% end %>
  <% end %>
<div class="panel panel-default">
        <div class="panel-heading">
            <%= action %>
            <%= link_to backoffice_admins_path, class:"btn btn-default btn-sm pull-right", style: "margin-top: -5px" do %>Voltar
            <% end %>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <div class="col-lg-6">
            <%= form_for ([:backoffice, @admin]) do |f| %>
              <div class="form-group">
              <label>Nome</label>
              <%= f.text_field :name, class:"form-control", placeholder:"Ex.: Nome" %>
              <label>Email</label>
              <%= f.text_field :email, class:"form-control", placeholder:"Ex.: admin@email.com" %>
              <label>Senha</label>
              <%= f.password_field :password, class:"form-control", placeholder:"A senha deve conter 6 caracteres" %>
              <label>Confirmar Senha</label>
              <%= f.password_field :password_confirmation, class:"form-control", placeholder:"A senha deve conter 6 caracteres" %>
              </div>
            <button type="submit" class="btn btn-default">Salvar</button>
            <% end %>
          </div>
        </div>
        <!-- /.panel-body -->
    </div>

app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Editar Categoria"} %>

app/views/backoffice/categories/index.html.erb
<h1 class="page-header">Categorias</h1>
<div class="panel panel-default">
        <div class="panel-heading">
            Categorias
            <%= link_to new_backoffice_category_path, class:"btn btn-success btn-sm pull-right", style: "margin-top: -5px" do %><i class="fa fa-plus"></i> Nova Categoria
            <% end %>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Descrição</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                    	<% @categories.each do |category| %>
                        <tr>
                            <td><%= category.id %></td>
                            <td><%= category.description %></td>
                            <td>
                                <%= link_to edit_backoffice_category_path(category),class:"btn btn-primary btn-circle" do %><i class="fa fa-edit"></i>
					                            <% end %>
					                            <button type="button" disabled class="btn btn-danger btn-circle"><i class="fa fa-times"></i>
					                            </button>
					                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>

app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Nova Categoria"} %>

app/views/backoffice/dashboard/index.html.erb
<h1 class="page-header">Dashboard</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escamboapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Escamboapp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>

  <div id="wrapper">
    <%= render partial: "layouts/backoffice_shared/navigation" %>
    <!-- Page Content -->
    <div id="page-wrapper">
    <div class="container-fluid">
      <div class="row">
          <div class="col-lg-12">
            <%= yield %>
          </div>
          <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->
  </div>
  <!-- /#wrapper -->

<% if notice %>
  <script>
    $.notify("<%= notice %>", "success");
  </script>
<% end %>

</body>

</html>

app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Escamboapp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>
    <%= yield %>
</body>

</html>

app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">BackOffice - EscamboApp</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_admin.email %>
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li>
                <%= link_to destroy_admin_session_path, method: :delete do %>
                <i class="fa fa-sign-out fa-fw"></i> 
                Sair
                <% end %>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                    <!-- /input-group -->
                </li>
                <li>
                    <%= link_to backoffice_dashboard_path do %>
                      <i class="fa fa-dashboard fa-fw"></i> Dashboard
                    <% end %>
                </li>
                <!-- <li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="flot.html">Flot Charts</a>
                        </li>
                        <li>
                            <a href="morris.html">Morris.js Charts</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level 
                </li> -->
                <li>
                  <%= link_to backoffice_categories_path do %>
                      <i class="fa fa-table fa-fw"></i> Categorias
                  <% end %>
                </li>
                <li>
                  <%= link_to backoffice_admins_path do %>
                      <i class="fa fa-users fa-fw"></i> Administradores
                  <% end %>
                </li>
                <li>
                    <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="panels-wells.html">Panels and Wells</a>
                        </li>
                        <li>
                            <a href="buttons.html">Buttons</a>
                        </li>
                        <li>
                            <a href="notifications.html">Notifications</a>
                        </li>
                        <li>
                            <a href="typography.html">Typography</a>
                        </li>
                        <li>
                            <a href="icons.html"> Icons</a>
                        </li>
                        <li>
                            <a href="grid.html">Grid</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="#">Second Level Item</a>
                        </li>
                        <li>
                            <a href="#">Second Level Item</a>
                        </li>
                        <li>
                            <a href="#">Third Level <span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                            </ul>
                            <!-- /.nav-third-level -->
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li class="active">
                    <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a class="active" href="blank.html">Blank Page</a>
                        </li>
                        <li>
                            <a href="login.html">Login Page</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EscamboApp</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'site', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'site', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render partial: "layouts/site_shared/navigation" %>
    <%= yield %>
    <%= render partial: "layouts/site_shared/footer" %>
  </body>

</html>

app/views/layouts/site_shared/_footer.html.erb
<div class="container">

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Start Bootstrap</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>